[package]
name = "rs-udp-thermo"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"

[[bin]]
name="indicator"
path= "src/indicator.rs"

[[bin]]
name="generator"
path="src/generator.rs"

